In [1]:
import numpy as np

# X -> (sleep hours, study hours)
X = np.array(([2,9], [1,5], [3,6]))

# Y -> (test score)
Y = np.array(([92], [86], [89]))

#scaling down values to keep within range 0.0 to 1.0
X = X/np.amax(X, axis=0)
Y = Y/100

In [2]:
class NeuralNetwork(object):
    
    def __init__(self):
        self.input_layers_size = 2
        self.hidden_layers_size = 3
        self.output_layers_size = 1
        
        # weight1 matrix -> between input and hidden layers
        self.w1 = np.random.randn(2,3)
        
        # weight2 matrix -> between hidden and output layers
        self.w2 = np.random.randn(3,1)
    
    
    def forward(self, X):
        self.z = np.dot(X, self.w1)
        self.z2 = 1/(1+np.exp(-self.z))
        self.z3 = np.dot(self.z2, self.w2)
        
        output = 1/(1+np.exp(-self.z3))
        return output
    
    def backward(self, X, Y, predicted_output):
        self.output_error = Y - predicted_output
        
        # derivative
        self.output_delta = self.output_error * (predicted_output * (1 - predicted_output))
        
        # contribution of hidden layers to output error
        self.z2_error = self.output_delta.dot(self.w2.T)
        
        # derivative
        self.z2_delta = self.z2_error * (self.z2 * (1 - self.z2))
        
        # adjust weight 1
        self.w1 += learning_rate * X.T.dot(self.z2_delta)
        
        #adjust weight 2
        self.w2 += learning_rate * self.z2.T.dot(self.output_delta)

In [3]:
NN = NeuralNetwork()

In [4]:
learning_rate = 0.1

for i in range(30):
    print("Epoch: ", i)
    print("Learning Rate: ", learning_rate)
    print("Input:\n", str(X))
    print("Actual Output:\n", str(Y))
    predicted_output = NN.forward(X)
    print("Predicted Output:\n", predicted_output)
    print("Loss:\n", str(np.mean(np.square(Y - predicted_output))))
    print("\n\n")
    
    NN.backward(X, Y, predicted_output)

Epoch:  0
Learning Rate:  0.1
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.45935461]
 [0.48529078]
 [0.39695729]]
Loss:
 0.1985640977769523



Epoch:  1
Learning Rate:  0.1
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.46605545]
 [0.49145044]
 [0.40374327]]
Loss:
 0.19278001432522193



Epoch:  2
Learning Rate:  0.1
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.47267783]
 [0.49753176]
 [0.41046994]]
Loss:
 0.18714314204094326



Epoch:  3
Learning Rate:  0.1
Input:
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output:
 [[0.47921939]
 [0.50353253]
 [0.41713367]]
Loss:
 0.18165305598194426



Epoch:  4
Lea